CREATE TABLE {0}persistents(
  PERSISTENT_ID BIGINT NOT NULL,
  TABLE_NAME CHAR(255) NOT NULL,
  TABLE_TYPE INTEGER NOT NULL,
  CLASS_NAME CHAR(255) NOT NULL,--full class name
  PLUGIN_NAME CHAR(255) NOT NULL,
  TYPE_NAME CHAR(255) NOT NULL,
  PERSISTENT_EXISTS BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT {0}persistents_pkey PRIMARY KEY (PERSISTENT_ID)
);

CREATE SEQUENCE {0}persistents_sequence START 1;

CREATE TABLE {0}persistent_fields
(
  PERSISTENT_FIELD_ID BIGINT NOT NULL,
  PERSISTENT_ID BIGINT NOT NULL,
  FIELD_NAME CHAR(255) NOT NULL,
  FIELD_DATABASE_NAME CHAR(255) NOT NULL,
  FIELD_ID INTEGER NOT NULL,
  FIELD_EXISTS BOOLEAN NOT NULL DEFAULT TRUE,
  FIELD_TYPE INTEGER NOT NULL,
  FIELD_AUTOSET BOOLEAN NOT NULL,
  FIELD_PRIMARY BOOLEAN NOT NULL,--PRIMARY_KEY
  CONSTRAINT {0}persistent_fields_pkey PRIMARY KEY (PERSISTENT_FIELD_ID),
  CONSTRAINT {0}persistent_fields_PERSISTENT_ID_fkey FOREIGN KEY (PERSISTENT_ID)
      REFERENCES {0}persistents (PERSISTENT_ID),
  CONSTRAINT {0}persistents_unique UNIQUE (PERSISTENT_ID, FIELD_ID)
);

CREATE SEQUENCE {0}persistent_fields_sequence START 1;

CREATE TABLE {0}application_preferencies
(
  OPTION_KEY CHAR(255) NOT NULL,
  OPTION_VALUE CHAR(255),
  CONSTRAINT {0}application_preferencies_fields_pkey PRIMARY KEY (OPTION_KEY)
);

CREATE TABLE {0}qualifiers
(
  QUALIFIER_ID BIGINT NOT NULL,
  QUALIFIER_NAME TEXT NOT NULL,
  QUALIFIER_SYSTEM BOOLEAN NOT NULL DEFAULT FALSE,
  ATTRIBUTE_FOR_NAME BIGINT,
  CONSTRAINT {0}qualifiers_fields_pkey PRIMARY KEY (QUALIFIER_ID)
);

CREATE SEQUENCE {0}qualifiers_sequence START 1;

CREATE UNIQUE INDEX {0}qualifiers_pkey_index ON {0}qualifiers(QUALIFIER_ID);

CREATE TABLE {0}elements
(
  ELEMENT_ID BIGINT NOT NULL,
  ELEMENT_NAME TEXT NOT NULL,
  QUALIFIER_ID BIGINT,
  CONSTRAINT {0}qualifiers_elements_pkey PRIMARY KEY (ELEMENT_ID),
  CONSTRAINT {0}elements_qualifier_id_fkey FOREIGN KEY (QUALIFIER_ID)
      REFERENCES {0}qualifiers (QUALIFIER_ID)
);

CREATE SEQUENCE {0}elements_sequence START 1;

CREATE UNIQUE INDEX {0}elements_pkey_index ON {0}elements(ELEMENT_ID);

CREATE INDEX {0}elements_fkey_index ON {0}elements(QUALIFIER_ID);

CREATE TABLE {0}attributes
(
  ATTRIBUTE_ID BIGINT NOT NULL,
  ATTRIBUTE_NAME TEXT NOT NULL,
  ATTRIBUTE_TYPE_PLUGIN_NAME CHAR(255) NOT NULL,
  ATTRIBUTE_TYPE_NAME CHAR(255) NOT NULL,
  ATTRIBUTE_TYPE_COMPARABLE BOOLEAN NOT NULL,
  ATTRIBUTE_SYSTEM BOOLEAN NOT NULL,
  CONSTRAINT {0}attributes_pkey PRIMARY KEY (ATTRIBUTE_ID)
);

CREATE SEQUENCE {0}attributes_sequence START 1;


CREATE TABLE {0}qualifiers_attributes
(
  QUALIFIER_ID BIGINT NOT NULL,
  ATTRIBUTE_ID BIGINT NOT NULL,
  ATTRIBUTE_SYSTEM BOOLEAN NOT NULL,
  CONSTRAINT {0}qualifiers_attributes_id_fkey FOREIGN KEY (QUALIFIER_ID)
      REFERENCES {0}qualifiers (QUALIFIER_ID),
  CONSTRAINT {0}attributes_qualifiers_id_fkey FOREIGN KEY (ATTRIBUTE_ID)
      REFERENCES {0}attributes (ATTRIBUTE_ID)
);

CREATE TABLE {0}streams(
  STREAM_ID TEXT NOT NULL
);
