package com.ramussoft.ai;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * DTO representing the structure of a diagram generated by the AI assistant.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class AiDiagramDefinition {

    private List<AiFunctionDefinition> functions = new ArrayList<AiFunctionDefinition>();

    private List<AiStreamDefinition> streams = new ArrayList<AiStreamDefinition>();

    private String notes;

    public List<AiFunctionDefinition> getFunctions() {
        return functions;
    }

    public void setFunctions(List<AiFunctionDefinition> functions) {
        if (functions == null) {
            this.functions = new ArrayList<AiFunctionDefinition>();
        } else {
            this.functions = functions;
        }
    }

    public List<AiStreamDefinition> getStreams() {
        return streams;
    }

    public void setStreams(List<AiStreamDefinition> streams) {
        if (streams == null) {
            this.streams = new ArrayList<AiStreamDefinition>();
        } else {
            this.streams = streams;
        }
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }
}
